
spring:
  #数据源
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wx_pay?useUnicode=true&characterEncoding=UTF-8&relaxAutoCommit=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9099
#mybatis配置
mybatis:
  typeAliasesPackage: com.xyz.wxpay.entity
  mapperLocations: classpath*:mapper/*.xml
  #configLocation: classpath:/mybatis-config.xml
# 打印sql
logging:
  level:
    com.xyz.wxpay.mapper : debug